CREATE PROCEDURE SP_ImportarConsorcio
    @RutaArchivo NVARCHAR(255)
AS
BEGIN
    SET NOCOUNT ON;

    CREATE TABLE #tmpTABLADECONSORCIOS(CAMPO_1 NVARCHAR(100), CAMPO_2 NVARCHAR(200), CAMPO_N NVARCHAR(100));
    DECLARE @sql NVARCHAR(MAX)=
        'BULK INSERT #tmpConsorcio
         FROM ''' + @RutaArchivo + '''
         WITH (FIELDTERMINATOR='','', ROWTERMINATOR=''\n'', FIRSTROW=2)';
    EXEC (@sql);
    INSERT INTO TABLADECONSORCIOS (CAMPOSDECONSORCIO)
    SELECT DISTINCT CAMPOSDECONSORCIO
    FROM #tmpTABLADECONSORCIOS AS t
    WHERE NOT EXISTS (
        SELECT 1 FROM TABLADECONSORCIOS c WHERE c.Nombre = t.Nombre
    );

    DROP TABLE #tmpTABLADECONSORCIOS;
END;
GO
